version: '3.8'

services:
  mongo1:
    image: mongo:4
    command: --replSet "rs0"
    volumes:
      - mongovol1:/data/db

  mongo2:
    image: mongo:4
    command: --replSet "rs0"
    volumes:
      - mongovol2:/data/db

  mongo3:
    image: mongo:4
    command: --replSet "rs0"
    volumes:
      - mongovol3:/data/db

  api:
    restart: always
    build: api
    image: docbuc/mwaapi:2
    environment:
      - MONGO_URL=mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0
      # - MONGO_URL=mongodb://mongo1:27017/
    depends_on:
      - mongo1
    ports:
      - 3000:3000

  redis:
    image: redis:6-alpine

  frontend:
    restart: always
    build: frontend
    image: docbuc/mwafe:2
    depends_on:
      - api
    ports:
      - 80:8080
      
volumes:
  mongovol1:
  mongovol2:
  mongovol3:

# docker-compose -f docker-compose.yml build frontend
# docker-compose exec frontend npm i --save-devvue2-dropzone
# docker-compose exec frontend npm rm --save-dev exif-reader
# docker-compose exec frontend npm i --save-dev @vue/eslint-config-standard
